### ISSUE TITLE
Error while waiting for response

### ISSUE THREAD

**Issue by driant** [fvdm/nodejs-gtmetrix#14]
Hi, 
I'm trying to do some tests with gtmetrix now but it looks like it has an error while waiting for the test results. Sometimes it works fine.
**I checked the poll_state_url after the error and it looked like this:**
{
"resources": {},
"error": "",
"results": {},
"state": "queued"
}

**Please check here for the console error**

if (err && !props.binary && !err.error.match (/Data not yet available/)) {
                                         ^
TypeError: err.error.match is not a function
    at pollingCallback (/home/driant/Projects/GTMetrixTests/node_modules/gtmetrix/index.js:166:42)
    at testGet (/home/driant/Projects/GTMetrixTests/node_modules/gtmetrix/index.js:267:24)
    at /home/driant/Projects/GTMetrixTests/node_modules/gtmetrix/index.js:245:7
    at apiResponse (/home/driant/Projects/GTMetrixTests/node_modules/gtmetrix/index.js:76:5)
    at http.doRequest (/home/driant/Projects/GTMetrixTests/node_modules/gtmetrix/index.js:128:5)
    at finalCallback (/home/driant/Projects/GTMetrixTests/node_modules/httpreq/lib/httpreq.js:98:7)
    at ClientRequest.<anonymous> (/home/driant/Projects/GTMetrixTests/node_modules/httpreq/lib/httpreq.js:422:7)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)

**Node version :  v6.11.2
Npm version:  3.10.10**

**Comment by hazemhagrass** [comment]
Any updates on this issue?

**Comment by fvdm** [comment]
Hi @hazemhagrass, sorry for taking so long. I was working on a fix, but ran out of time. It is postponed till I get some space in my schedule.

**Comment by fvdm** [comment]
I pushed a quick fix to develop branch and it seems to work fine. Could you please confirm this resolves the error in your own use case?

`npm i fvdm/nodejs-gtmetrix#develop`

**Comment by StefanMichalke** [comment]
Hi Franklin,
I have the same error and it seems that your fix doesn't work :-(

![error match_function](https://user-images.githubusercontent.com/29750584/36854584-a7205092-1d71-11e8-9a7e-5fe53f1a9fc0.png)

**Comment by fvdm** [comment]
Hi, thanks for reporting! I have now redone the polling callback handing. That code was so messed up. Could you please retry:

`npm i fvdm/nodejs-gtmetrix#patch-14`

**Comment by fvdm** [comment]
Actually, I did a whole bunch of edits and pushed a fix that should really work to npm. Please let me know if it works or is still broken. The tests are all green.

`npm i gtmetrix`

**Comment by StefanMichalke** [comment]
Hi,
After deleting node_modules and reinstall it seems that it works :-)
But a strange behaviour I found:
I have the following configuration:
`var gtmetrix = require ('gtmetrix') ({
  email: 'your@mail.tld',
  apikey: 'abc123',
});`
without 'Timeout'
in this case i get an error.
I must use the timeout:
`var gtmetrix = require ('gtmetrix') ({
  email: 'your@mail.tld',
  apikey: 'abc123',
  timeout: 10000
});`
maybe you should update your documentation
- required = yes

many thanks for fixing!!

**Comment by fvdm** [comment]
Oops, that's a bug. I fixed it in v1.2.7 which is now on npm.

Running `npm update` in your package path should do the trick and avoid having to delete the whole node_modules dir.
